version: 3
jobs:
  beta:
    macos:
      xcode: "11.0.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: "v2-gems"
      - run:
          name: Install with bundler
          command: bundle check || bundle install --path .bundle
      - save_cache:
          key: "v2-gems"
          paths: ["./.bundle"]
      # Download CocoaPods specs via HTTPS (faster than Git or `pod outdated`)
      - run:
          name: Update CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: bundle exec pod install --verbose
      - run:
          name: Install with bundler
          command: bundle check || bundle install --path .bundle
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
  build-and-test:
    macos:
      xcode: "10.2.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: "v2-gems"
      - run:
          name: Install with bundler
          command: bundle check || bundle install --path .bundle
      - save_cache:
          key: "v2-gems"
          paths: ["./.bundle"]
      # Download CocoaPods specs via HTTPS (faster than Git or `pod outdated`)
      - run:
          name: Update CocoaPods Specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Install CocoaPods
          command: bundle exec pod install --verbose
      - run:
          name: pre-start simulator
          command: xcrun instruments -w "iPhone X (12.0) [" || true
      - run:
          name: Fastlane
          command: bundle exec fastlane test

workflows:
  version: 2
  build-upload-testflight:
    jobs:
      - beta:
          filters:
            tags:
              only: /^beta-tf.*/
            branches:
              ignore: /.*/
  build-test-adhoc:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - /feature/.*/
                - /release/.*/
                - /fix/.*/
                - /refactor/.*/
                - /bugfix/.*/
